//run from powershell by writing node convertfile.js
//if multiple files, new profanity words or similar, it should be easy to add by just adding the file and then looping over that file as well
const fs = require('fs');
let profanity_words = 'val profanity_list = ['

const eng = fs.readFileSync('eng.txt', 'utf8');
eng.split(/\r?\n/).forEach(line =>  {
  profanity_words = profanity_words.concat(`'${line}', `)
});

const french = fs.readFileSync('french.txt', 'utf8');
french.split(/\r?\n/).forEach(line =>  {
  profanity_words = profanity_words.concat(`'${line}', `)
});

//add new langauge here

profanity_words = profanity_words.slice(0, -2); //remove last ', ', will generate syntax error else 
profanity_words = profanity_words.concat('];')

fs.writeFileSync('../rell/src/profanity_filter/words/profanity.rell', 
    '//OBS this is autogenerated, don\'t update here, see listconvertion folder' +
    '\nfunction profanity_words() : set<text> {' +
    '\n\t' + profanity_words +
    '\n\tval profanity_set = set<text>();' +
    '\n\tprofanity_set.add_all(profanity_list);' +
    '\n\treturn profanity_set;' +
    '\n}'
)
